// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZS68LCs2RSzIz8Nk_EmXzMIggO0glWQ',
    appId: '1:779853414912:web:403cb4f4351b87649bcee5',
    messagingSenderId: '779853414912',
    projectId: 'veggiefresh-5c80e',
    authDomain: 'veggiefresh-5c80e.firebaseapp.com',
    storageBucket: 'veggiefresh-5c80e.firebasestorage.app',
    measurementId: 'G-E47B8LE77G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALgNeDkYImNCyQ6BGjghhneaP7k-Deq04',
    appId: '1:779853414912:android:d42f82f6721b9b5e9bcee5',
    messagingSenderId: '779853414912',
    projectId: 'veggiefresh-5c80e',
    storageBucket: 'veggiefresh-5c80e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJxtsKqx0fhfkoVMgml3bgjl3f6CGDk4Q',
    appId: '1:779853414912:ios:161b4be8a5ea88b59bcee5',
    messagingSenderId: '779853414912',
    projectId: 'veggiefresh-5c80e',
    storageBucket: 'veggiefresh-5c80e.firebasestorage.app',
    iosBundleId: 'com.veggiefresh.veggiefresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJxtsKqx0fhfkoVMgml3bgjl3f6CGDk4Q',
    appId: '1:779853414912:ios:161b4be8a5ea88b59bcee5',
    messagingSenderId: '779853414912',
    projectId: 'veggiefresh-5c80e',
    storageBucket: 'veggiefresh-5c80e.firebasestorage.app',
    iosBundleId: 'com.veggiefresh.veggiefresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdZS68LCs2RSzIz8Nk_EmXzMIggO0glWQ',
    appId: '1:779853414912:web:82d9fa59ddb37e129bcee5',
    messagingSenderId: '779853414912',
    projectId: 'veggiefresh-5c80e',
    authDomain: 'veggiefresh-5c80e.firebaseapp.com',
    storageBucket: 'veggiefresh-5c80e.firebasestorage.app',
    measurementId: 'G-XL2JXJPHQ4',
  );
}
